name: PitchBlack [PBRP]

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'PBRP Manifest Branch'
        required: true
        default: 'android-12.1'
        type: choice
        options:
        - android-14.0
        - android-12.1
      DEVICE_TREE:
        description: 'Custom Recovery Tree'
        required: true
        default: 'https://github.com/IsaacCodesStuff/android_device_samsung_a06_twrp.git'
      DEVICE_TREE_BRANCH:
        description: 'Custom Recovery Tree Branch'
        required: true
        default: 'android-12.1'
      BUILD_TARGET:
        description: 'Specify your Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
        - boot
        - recovery
        - vendor_boot
      LDCHECK:
        description: 'Use LDCHECK'
        required: false
        type: boolean
      LDCHECKPATH:
        description: 'Path of blobs to check'
        required: true
        default: 'system/bin/stk_rec_bypass'

jobs:
  build:
    name: Build PBRP by ${{ github.actor }}
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v6
      
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24

    - name: Build PitchBlack Recovery
      uses: mlm-games/pitchblack-pbrp-builder-action@main
      id: build
      with:
        MANIFEST_BRANCH: ${{ inputs.MANIFEST_BRANCH }}
        DEVICE_TREE:  ${{ inputs.DEVICE_TREE }}
        DEVICE_TREE_BRANCH:  ${{ inputs.DEVICE_TREE_BRANCH }}
        BUILD_TARGET:  ${{ inputs.BUILD_TARGET }}
  
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      if: inputs.upload_releases == false || github.event_name != 'workflow_dispatch'
      with:
        name: PBRP-Recovery-${{ env.DEVICE_NAME }}-${{ env.BUILD_DATE }}
        path: |
          ${{ env.OUTPUT_DIR }}/*.img
          ${{ env.OUTPUT_DIR }}/*.tar
          ${{ env.OUTPUT_DIR }}/*vbmeta*
          ${{ env.OUTPUT_DIR }}/*.cpio

    - name: Upload to Release
      if: success()
      uses: softprops/action-gh-release@master
      with:
        files: |
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/${{ inputs.BUILD_TARGET }}.img
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/*installer*zip
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/ramdisk-recovery.*
          android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/vbmeta.*
        name: Unofficial TWRP for ${{ inputs.DEVICE_NAME }} // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
          Build: ${{ inputs.MANIFEST_BRANCH }}
          Device: [Device Tree/Branch](${{ inputs.DEVICE_TREE }}/tree/${{ inputs.DEVICE_TREE_BRANCH }})
          Commit: Most recent [commit](${{ inputs.DEVICE_TREE }}/commit/${{ env.COMMIT_ID }}) during building.
        prerelease: false

    - name: Run LDCheck
      if: inputs.LDCHECK == 'true'
      run: |
        cd tools
        mv -n libneeds ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/recovery/root/
        mv -n ldcheck ${GITHUB_WORKSPACE}/android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/recovery/root/
        cd ../android-recovery/out/target/product/${{ inputs.DEVICE_NAME }}/recovery/root
        python3 ldcheck -p system/lib64:vendor/lib64:system/lib:vendor/lib -d ${{ inputs.LDCHECKPATH }}
        echo "Done checking missing dependencies. Review, and reconfigure your tree."
      continue-on-error: true
